appName: cvapipe_analysis

project:
    local_staging: "/allen/aics/assay-dev/MicroscopyOtherData/Viana/projects/cvapipe_analysis/local_staging_full"
    overwrite: off

data:
    cell:
        alias: MEM
        channel: membrane_segmentation
        color: '#F200FF'
    nucleus:
        alias: NUC
        channel: dna_segmentation
        color: '#3AADA7'
    structure:
        alias: STR
        channel: struct_segmentation_roof
        color: '#000000'

features:
    aliases: ["NUC", "MEM", "STR"]
    # SHE - Spherical harmonics expansion
    SHE:
        alignment:
            align: on
            unique: off
            reference: "cell"
        aliases: ["NUC", "MEM"]
        # Size of Gaussian kernal used to smooth the
        # images before SHE coefficients calculation
        sigma: 2
        # Number of SHE coefficients used to describe cell
        # and nuclear shape
        lmax: 16

preprocessing:
    remove_mitotics: on
    remove_outliers: on
    filtering:
        filter: off
        csv: "/allen/aics/assay-dev/MicroscopyOtherData/Viana/projects/cvapipe_analysis/local_staging_goldilock/loaddata/manifest.csv"
        specs: {"track_type": ["F"]}

shapespace:
    # Specify the a set of aliases here
    aliases: ["NUC", "MEM"]
    # Sort shape modes by volume of
    sorter: "MEM"
    # Percentage of exteme points to be removed
    removal_pct: 1.0
    # Number of principal components to be calculated
    number_of_shape_modes: 8
    # Map points
    map_points: [-2.0, -1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0]
    plot:
        frame: on
        swapxy_on_zproj: off
        # limits of x and y axies in the animated GIFs
        limits: [-150, 150, -80, 80]
    
parameterization:
    inner: "NUC"
    outer: "MEM"
    parameterize: ["RAWSTR", "STR"]
    number_of_interpolating_points: 32

aggregation:
    type: ['avg']

structures:
    "FBL": ["nucleoli [DFC)", "#A9D1E5", "{'raw': (960, 3500), 'seg': (20,100)}"]
    "NPM1": ["nucleoli [GC)", "#88D1E5", "{'raw': (1000, 9000), 'seg': (20,100)}"]
    "SON": ["nuclear speckles", "#3292C9", "{'raw': (370, 1100), 'seg': (10,100)}"]
    "SMC1A": ["cohesins", "#306598", "{'raw': (450, 700), 'seg': (0,70)}"]
    "HIST1H2BJ": ["histones", "#305098", "{'raw': (400, 3000), 'seg': (5,60)}"]
    "LMNB1": ["nuclear envelope", "#084AE7", "{'raw': (400,1600), 'seg': (5,60)}"]
    "NUP153": ["nuclear pores", "#0840E7", "{'raw': (400, 700), 'seg': (5,60)}"]
    "SEC61B": ["ER [Sec61 beta)", "#FFFFB5", "{'raw': (400,1000), 'seg': (1,40)}"]
    "ATP2A2": ["ER [SERCA2)", "#FFFFA0", "{'raw': (400,700), 'seg': (1,40)}"]
    "TOMM20": ["mitochondria", "#FFD184", "{'raw': (400,700), 'seg': (0,18)}"]
    "SLC25A17": ["peroxisomes", "#FFD16E", "{'raw': (400,550), 'seg': (100,150)}"]
    "RAB5A": ["endosomes", "#FFD150", "{'raw': (400,550), 'seg': (0,40)}"]
    "LAMP1": ["lysosomes", "#AD952A", "{'raw': (400,760), 'seg': (0,20)}"]
    "ST6GAL1": ["Golgi", "#B7952A", "{'raw': (400,500), 'seg': (0,30)}"]
    "CETN2": ["centrioles", "#9D7000", "{'raw': (400,600), 'seg': (0,25)}"]
    "TUBA1B": ["microtubules", "#6B4500", "{'raw': (1200,3200), 'seg': (0,12)}"]
    "AAVS1": ["plasma membrane", "#FFD2FF", "{'raw': (400,2000), 'seg': (1,30)}"]
    "ACTB": ["actin filaments", "#FFB1FF", "{'raw': (490,1490), 'seg': (0,50)}"]
    "ACTN1": ["actin bundles", "#FF96FF", "{'raw': (440,790), 'seg': (0,20)}"]
    "MYH10": ["actomyosin bundles", "#FF82FF", "{'raw': (600,1100), 'seg': (0,20)}"]
    "GJA1": ["gap junctions", "#A850C0", "{'raw': (260,2680), 'seg': (0,70)}"]
    "TJP1": ["tight junctions", "#A850D4", "{'raw': (250,1500), 'seg': (0,50)}"]
    "DSP": ["desmosomes", "#A850E8", "{'raw': (390,540), 'seg': (0,30)}"]
    "CTNNB1": ["adherens junctions", "#CB1CCC", "{'raw': (400,880), 'seg': (1,40)}"]
    "PXN": ["matrix adhesions", "#77207C", "{'raw': (410,470), 'seg': (0,70)}"]

distribute:
    # In case a (slurm) cluster is available
    cores: 30
    number_of_workers: 12
    memory: "8GB"
    queue: "aics_cpu_general"
    walltime: "9-24:00:00"
    python_env: "/home/matheus.viana/anaconda3/envs/cvapipe/"
