appName: cvapipe_analysis

project:
    # Sufix to append to local_staging
    name: "test"

resources:
    # In case a (slurm) cluster is available
    cores: 30
    nworkers: 32
    memory: "8GB"
    queue: "aics_cpu_general"
    walltime: "9-24:00:00"
    path_python_env: "/home/matheus.viana/anaconda3/envs/cvapipe/bin/python"

pca:
    # Number of principal components to be calculated
    number_of_pcs: 8
    # Number of map points along each principal component
    number_map_points: 9
    # limits of x and y axies in the animated GIFs
    plot_limits: [-150, 150, -80, 80]

aggregation:
    type: ['avg']
    # Shape space used to create aggregated images.
    # Choices are:
    # DNA_PC: shape space of nucleus alone
    # MEM_PC: shape space of cell alone
    # DNA_MEM_PC: shape space of nucleus and cell together
    aggregate_on: "DNA_MEM_PC"


parameterization:
    # List of images and their channels that should be
    # parameterized
    intensities: [['crop_raw', 'structure'], ['crop_seg', 'structure_seg']]
    # Number of SHE coefficients used to describe cell
    # and nuclear shape
    lmax: 16
    # Number of interplation points between nuclear
    # centroid and nuclear shell, and from nuclear
    # shell to cell membrane.
    nisos: [32, 32]

structures:

    # >> Results are going to be ordered according to
    # this sequence. These match the column structure_name
    # in the manifest.
    genes: ["FBL", "NPM1", "SON", "SMC1A", "HIST1H2BJ", "LMNB1", "NUP153", "SEC61B", "ATP2A2", "TOMM20", "SLC25A17", "RAB5A", "LAMP1",  "ST6GAL1", "CETN2", "TUBA1B", "AAVS1", "ACTB", "ACTN1", "MYH10", "GJA1", "TJP1", "DSP", "CTNNB1", "PXN"]
    # Mapping between gene name and description
    desc:
        "FBL": "nucleoli (DFC)"
        "NPM1": "nucleoli (GC)"
        "SON": "nuclear speckles"
        "SMC1A": "cohesins"
        "HIST1H2BJ": "histones"
        "LMNB1": "nuclear envelope"
        "NUP153": "nuclear pores"
        "SEC61B": "ER (Sec61 beta)"
        "ATP2A2": "ER (SERCA2)"
        "TOMM20": "mitochondria"
        "SLC25A17": "peroxisomes"
        "RAB5A": "endosomes"
        "LAMP1": "lysosomes"
        "ST6GAL1": "Golgi"
        "CETN2": "centrioles"
        "TUBA1B": "microtubules"
        "AAVS1": "plasma membrane"
        "ACTB": "actin filaments"
        "ACTN1": "actin bundles"
        "MYH10": "actomyosin bundles"
        "CTNNB1": "adherens junctions"
        "GJA1": "gap junctions"
        "TJP1": "tight junctions"
        "DSP": "desmosomes"
        "PXN": "matrix adhesions"
