appName: cvapipe_analysis

project:
    # Sufix to append to local_staging
    local_staging: "/allen/aics/assay-dev/MicroscopyOtherData/Viana/projects/cvapipe_analysis/local_staging_full"
    overwrite: on

data:
    nucleus:
        channel: "dna_segmentation"
        alias: "NUC"
        color: "#3AADA7"

features:
    aliases: ["NUC"]
    # SHE - Spherical harmonics expansion
    SHE:
        alignment:
            align: on
            unique: off
            reference: "nucleus"
        aliases: ["NUC"]
        # Size of Gaussian kernal used to smooth the
        # images before SHE coefficients calculation
        sigma: 2
        # Number of SHE coefficients used to describe cell
        # and nuclear shape
        lmax: 16

preprocessing:
    remove_mitotics: on
    remove_outliers: on

shapespace:
    # Specify the a set of aliases here
    aliases: ["NUC"]
    # Sort shape modes by volume of
    sorter: "NUC"
    # Percentage of exteme points to be removed
    removal_pct: 1.0
    # Number of principal components to be calculated
    number_of_shape_modes: 8
    # Map points
    map_points: [-2.0, -1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0]
    plot:
        swapxy_on_zproj: off
        # limits of x and y axies in the animated GIFs
        limits: [-150, 150, -80, 80]
    
parameterization:
    inner: "NUC"
    outer: "MEM"
    parameterize: ["RAWSTR", "STR"]
    number_of_interpolating_points: 32

aggregation:
    type: ['avg']

structures:
    "FBL": ["nucleoli [DFC)", "#A9D1E5"]
    "NPM1": ["nucleoli [GC)", "#88D1E5"]
    "SON": ["nuclear speckles", "#3292C9"]
    "SMC1A": ["cohesins", "#306598"]
    "HIST1H2BJ": ["histones", "#305098"]
    "LMNB1": ["nuclear envelope", "#084AE7"]
    "NUP153": ["nuclear pores", "#0840E7"]
    "SEC61B": ["ER [Sec61 beta)", "#FFFFB5"]
    "ATP2A2": ["ER [SERCA2)", "#FFFFA0"]
    "TOMM20": ["mitochondria", "#FFD184"]
    "SLC25A17": ["peroxisomes", "#FFD16E"]
    "RAB5A": ["endosomes", "#FFD150"]
    "LAMP1": ["lysosomes", "#AD952A"]
    "ST6GAL1": ["Golgi", "#B7952A"]
    "CETN2": ["centrioles", "#9D7000"]
    "TUBA1B": ["microtubules", "#6B4500"]
    "AAVS1": ["plasma membrane", "#FFD2FF"]
    "ACTB": ["actin filaments", "#FFB1FF"]
    "ACTN1": ["actin bundles", "#FF96FF"]
    "MYH10": ["actomyosin bundles", "#FF82FF"]
    "GJA1": ["gap junctions", "#A850C0"]
    "TJP1": ["tight junctions", "#A850D4"]
    "DSP": ["desmosomes", "#A850E8"]
    "CTNNB1": ["adherens junctions", "#CB1CCC"]
    "PXN": ["matrix adhesions", "#77207C"]

distribute:
    # In case a (slurm) cluster is available
    cores: 30
    number_of_workers: 32
    memory: "8GB"
    queue: "aics_cpu_general"
    walltime: "9-24:00:00"
    python_env: "/home/matheus.viana/anaconda3/envs/cvapipe/"
