appName: cvapipe_analysis

project:
    local_staging: "your_path_to/local_staging_variance"
    overwrite: off

data:
    cell:
        alias: MEM
        channel: membrane_segmentation
        color: '#F200FF'
    cell-roof:
        alias: MEMROOF
        channel: membrane_segmentation_roof
        color: '#F200FF'
    nucleus:
        alias: NUC
        channel: dna_segmentation
        color: '#3AADA7'
    structure:
        alias: STR
        channel: struct_segmentation_roof
        color: '#000000'
    raw-structure-str:
        alias: RAWSTR_MASKEDBY_STR
        channel: structure
        color: '#000000'
    raw-structure-nuc:
        alias: RAWSTR_MASKEDBY_NUC
        channel: structure
        color: '#000000'
    raw-structure-mem:
        alias: RAWSTR_MASKEDBY_MEM
        channel: structure
        color: '#000000'

features:
    aliases: ["NUC", "MEM", "STR", "RAWSTR_MASKEDBY_STR", "RAWSTR_MASKEDBY_NUC", "RAWSTR_MASKEDBY_MEM"]
    # Intensity features: specify aliases for raw image and
    # corresponding segmentation mask.
    intensity:
        RAWSTR_MASKEDBY_STR: STR
        RAWSTR_MASKEDBY_NUC: NUC
        RAWSTR_MASKEDBY_MEM: MEMROOF
    # SHE - Spherical harmonics expansion
    SHE:
        alignment:
            align: on
            unique: off
            reference: "cell"
        aliases: ["NUC", "MEM"]
        # Size of Gaussian kernal used to smooth the
        # images before SHE coefficients calculation
        sigma:
            MEM: 2
            NUC: 2
        # Number of SHE coefficients used to describe cell
        # and nuclear shape
        lmax: 16

preprocessing:
    remove_mitotics: on
    remove_outliers: on
    filtering:
        filter: off
        csv: ""
        specs: {}

shapespace:
    # Specify the a set of aliases here
    aliases: ["NUC", "MEM"]
    # Sort shape modes by volume of
    sorter: "MEM"
    # Percentage of exteme points to be removed
    removal_pct: 1.0
    # Number of principal components to be calculated
    number_of_shape_modes: 8
    # Map points
    map_points: [-2.0, -1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0]
    plot:
        frame: on
        swapxy_on_zproj: off
        # limits of x and y axies in the animated GIFs
        limits: [-150, 150, -80, 80]
    
parameterization:
    inner: "NUC"
    outer: "MEM"
    parameterize: ["STR"]
    number_of_interpolating_points: 32

aggregation:
    type: ['avg']

structures:
    "FBL": ["nucleoli [DFC)", "#A9D1E5", "{'raw': (420, 2610), 'seg': (0,30), 'avgseg': (80,160)}"]
    "NPM1": ["nucleoli [GC)", "#88D1E5", "{'raw': (480, 8300), 'seg': (0,30), 'avgseg': (80,160)}"]
    "SON": ["nuclear speckles", "#3292C9", "{'raw': (420, 1500), 'seg': (0,10), 'avgseg': (10,60)}"]
    "SMC1A": ["cohesins", "#306598", "{'raw': (450, 630), 'seg': (0,2), 'avgseg': (0,15)}"]
    "HIST1H2BJ": ["histones", "#305098", "{'raw': (450, 2885), 'seg': (0,30), 'avgseg': (10,100)}"]
    "LMNB1": ["nuclear envelope", "#084AE7", "{'raw': (475,1700), 'seg': (0,30), 'avgseg': (0,60)}"]
    "NUP153": ["nuclear pores", "#0840E7", "{'raw': (420, 600), 'seg': (0,15), 'avgseg': (0,50)}"]
    "SEC61B": ["ER [Sec61 beta)", "#FFFFB5", "{'raw': (490,1070), 'seg': (0,30), 'avgseg': (0,100)}"]
    "ATP2A2": ["ER [SERCA2)", "#FFFFA0", "{'raw': (430,670), 'seg': (0,25), 'avgseg': (0,80)}"]
    "SLC25A17": ["peroxisomes", "#FFD184", "{'raw': (400,515), 'seg': (0,7), 'avgseg': (0,15)}"]
    "RAB5A": ["endosomes", "#FFC846", "{'raw': (420,600), 'seg': (0,7), 'avgseg': (0,10)}"]
    "TOMM20": ["mitochondria", "#FFBE37", "{'raw': (410,815), 'seg': (0,27), 'avgseg': (0,50)}"]
    "LAMP1": ["lysosomes", "#AD952A", "{'raw': (440,800), 'seg': (0,27), 'avgseg': (0,30)}"]
    "ST6GAL1": ["Golgi", "#B7952A", "{'raw': (400,490), 'seg': (0,17), 'avgseg': (0,30)}"]
    "TUBA1B": ["microtubules", "#9D7000", "{'raw': (1100,3200), 'seg': (0,22), 'avgseg': (0,60)}"]
    "CETN2": ["centrioles", "#C8E1AA", "{'raw': (440,800), 'seg': (0, 2), 'avgseg': (0,2)}"]
    "GJA1": ["gap junctions", "#BEE18C", "{'raw': (420,2200), 'seg': (0,4), 'avgseg': (0,8)}"]
    "TJP1": ["tight junctions", "#B4C878", "{'raw': (420,1500), 'seg': (0,8), 'avgseg': (0,20)}"]
    "DSP": ["desmosomes", "#B4C864", "{'raw': (410,620), 'seg': (0,5), 'avgseg': (0,3)}"]
    "CTNNB1": ["adherens junctions", "#96AA46", "{'raw': (410,750), 'seg': (0,22), 'avgseg': (5,40)}"]
    "AAVS1": ["plasma membrane", "#FFD2FF", "{'raw': (505,2255), 'seg': (0,30), 'avgseg': (10,120)}"]
    "ACTB": ["actin filaments", "#E6A0FF", "{'raw': (550,1300), 'seg': (0,18), 'avgseg': (0,35)}"]
    "ACTN1": ["actin bundles", "#E696FF", "{'raw': (440,730), 'seg': (0,13), 'avgseg': (0,25)}"]
    "MYH10": ["actomyosin bundles", "#FF82FF", "{'raw': (440,900), 'seg': (0,13), 'avgseg': (0,25)}"]
    "PXN": ["matrix adhesions", "#CB1CCC", "{'raw': (410,490), 'seg': (0,5), 'avgseg': (0,5)}"]

distribute:
    # In case a (slurm) cluster is available
    cores: 30
    number_of_workers: 16
    memory: "8GB"
    queue: "aics_cpu_general"
    walltime: "9-24:00:00"
    python_env: "/home/matheus.viana/anaconda3/envs/cvapipe/"