name: Test and Lint

on:
 pull_request:
 # If merge queues are enabled, test against the result of a merge before finalizing the merge
 merge_group:
 workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Test with pytest
      run: |
        pytest cvapipe_analysis/tests/
    - name: Upload codecov
      uses: codecov/codecov-action@125fc84a9a348dbcf27191600683ec096ec9021c

  #lint:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
  #  - name: Set up Python
  #    uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
  #    with:
  #      python-version: 3.9
  #  - name: Install Dependencies
  #    run: |
  #      python -m pip install --upgrade pip
  #      pip install .[test]
  #  - name: Lint with flake8
  #    run: |
  #      flake8 cvapipe_analysis --count --verbose --show-source --statistics
  #  - name: Check with black
  #    run: |
  #      black --check cvapipe_analysis