name: Test and Lint

on:
 pull_request:
 # If merge queues are enabled, test against the result of a merge before finalizing the merge
 merge_group:
 workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Test with pytest
      run: |
        pytest cvapipe_analysis/tests/
    - name: Upload codecov
      uses: codecov/codecov-action@c16abc29c95fcf9174b58eb7e1abf4c866893bc8

  #lint:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
  #  - name: Set up Python
  #    uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
  #    with:
  #      python-version: 3.9
  #  - name: Install Dependencies
  #    run: |
  #      python -m pip install --upgrade pip
  #      pip install .[test]
  #  - name: Lint with flake8
  #    run: |
  #      flake8 cvapipe_analysis --count --verbose --show-source --statistics
  #  - name: Check with black
  #    run: |
  #      black --check cvapipe_analysis